CREATE TABLE IF NOT EXISTS `vehicle_sources` (
	`id` text PRIMARY KEY NOT NULL,
	`vehicle_id` text NOT NULL,
	`name` text NOT NULL,
	`seller` text,
	`price` integer,
	`url` text,
	`last_verified` text,
	`status` text DEFAULT 'Needs verification' NOT NULL,
	FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `vehicle_timeline` (
	`id` text PRIMARY KEY NOT NULL,
	`vehicle_id` text NOT NULL,
	`time` text NOT NULL,
	`label` text NOT NULL,
	`detail` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `vehicles` (
	`id` text PRIMARY KEY NOT NULL,
	`stock_no` text NOT NULL,
	`brand` text NOT NULL,
	`model` text NOT NULL,
	`year` text,
	`grade` text,
	`engine` text,
	`engine_capacity` text,
	`transmission` text,
	`drive` text,
	`body` text,
	`cab_type` text,
	`mileage` text,
	`color` text,
	`registration_year` text,
	`source_price` integer,
	`selling_price` integer,
	`last_sold_price` integer,
	`sold_month` text,
	`destination` text,
	`state` text DEFAULT 'Waiting Review' NOT NULL,
	`availability_verified` integer DEFAULT 0 NOT NULL,
	`possible_duplicate` text,
	`plate_masked` text,
	`vin_masked` text,
	`vin_chassis` text,
	`image` text,
	`cover_image` text,
	`images` text,
	`seller` text,
	`source_platform` text,
	`listing_text` text,
	`location` text,
	`source_import` text,
	`ai_summary` text,
	`confidence` text,
	`ai_meta` text,
	`corrections` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
