import type { CustomerListing } from "../types";

export const autoPublishedCustomerListings: CustomerListing[] = [
  {
    "id": "nk-auto-20260912-01",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-01",
    "title": "2022 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2022 ราคาจากประกาศ 475,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2022,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 475000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-01.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-02",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-02",
    "title": "2025 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2025 ราคาจากประกาศ 388,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2025,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 388000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-02.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-03",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-03",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 550,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 550000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-03.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-04",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-04",
    "title": "2024 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2024 ราคาจากประกาศ 455,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2024,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 455000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-04.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-05",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-05",
    "title": "2023 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2023 ราคาจากประกาศ 799,999 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2023,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 799999,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-05.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-06",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-06",
    "title": "2025 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2025 ราคาจากประกาศ 1,079,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2025,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 1079000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-06.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-07",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-07",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 375,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 375000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-07.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-08",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-08",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 659,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 659000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-08.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-09",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-09",
    "title": "2025 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2025 ราคาจากประกาศ 389,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2025,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 389000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-09.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-10",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-10",
    "title": "2022 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2022 ราคาจากประกาศ 479,999 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2022,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 479999,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-10.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-11",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-11",
    "title": "2022 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2022 ราคาจากประกาศ 539,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2022,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 539000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-11.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-12",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-12",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 459,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 459000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-12.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-13",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-13",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 485,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 485000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-13.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-14",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-14",
    "title": "2021 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2021 ราคาจากประกาศ 589,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2021,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 589000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-14.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-15",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-15",
    "title": "2016 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2016 ราคาจากประกาศ 499,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2016,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 499000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-15.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-16",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-16",
    "title": "2020 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2020 ราคาจากประกาศ 355,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2020,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 355000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-16.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-17",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-17",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 339,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 339000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-17.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-18",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-18",
    "title": "2021 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2021 ราคาจากประกาศ 799,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2021,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 799000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-18.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-19",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-19",
    "title": "2018 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2018 ราคาจากประกาศ 375,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2018,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 375000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-19.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-20",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-20",
    "title": "2016 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2016 ราคาจากประกาศ 195,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2016,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 195000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-20.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-21",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-21",
    "title": "2021 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2021 ราคาจากประกาศ 610,230 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2021,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 610230,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-21.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-22",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-22",
    "title": "2018 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2018 ราคาจากประกาศ 400,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2018,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 400000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-22.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-23",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-23",
    "title": "2018 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2018 ราคาจากประกาศ 992,018 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2018,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 992018,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-23.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-24",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-24",
    "title": "2017 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2017 ราคาจากประกาศ 640,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2017,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 640000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-24.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-25",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-25",
    "title": "2022 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2022 ราคาจากประกาศ 659,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2022,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 659000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-25.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-26",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-26",
    "title": "2022 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2022 ราคาจากประกาศ 599,900 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2022,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 599900,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-26.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-27",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-27",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 759,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 759000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-27.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-28",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-28",
    "title": "2024 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2024 ราคาจากประกาศ 699,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2024,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 699000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-28.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-29",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-29",
    "title": "2016 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2016 ราคาจากประกาศ 375,900 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2016,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 375900,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-29.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-30",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-30",
    "title": "2020 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2020 ราคาจากประกาศ 255,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2020,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 255000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-30.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-31",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-31",
    "title": "2018 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2018 ราคาจากประกาศ 599,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2018,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 599000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-31.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-32",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-32",
    "title": "2018 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2018 ราคาจากประกาศ 739,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2018,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 739000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-32.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-33",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-33",
    "title": "2022 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2022 ราคาจากประกาศ 525,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2022,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 525000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-33.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-34",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-34",
    "title": "2020 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2020 ราคาจากประกาศ 379,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2020,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 379000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-34.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-35",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-35",
    "title": "2021 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2021 ราคาจากประกาศ 569,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2021,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 569000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-35.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-36",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-36",
    "title": "2020 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2020 ราคาจากประกาศ 489,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2020,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 489000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-36.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-37",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-37",
    "title": "2018 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2018 ราคาจากประกาศ 339,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2018,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 339000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-37.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-38",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-38",
    "title": "2020 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2020 ราคาจากประกาศ 372,020 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2020,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 372020,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-38.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-39",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-39",
    "title": "2020 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2020 ราคาจากประกาศ 379,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2020,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 379000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-39.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-40",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-40",
    "title": "2023 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2023 ราคาจากประกาศ 395,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2023,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 395000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-40.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-41",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-41",
    "title": "2022 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2022 ราคาจากประกาศ 645,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2022,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 645000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-41.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-42",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-42",
    "title": "2018 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2018 ราคาจากประกาศ 992,018 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2018,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 992018,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-42.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-43",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-43",
    "title": "2020 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2020 ราคาจากประกาศ 379,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2020,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 379000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-43.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-44",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-44",
    "title": "2017 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2017 ราคาจากประกาศ 395,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2017,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 395000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-44.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-45",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-45",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 360,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 360000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-45.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-46",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-46",
    "title": "2021 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2021 ราคาจากประกาศ 429,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2021,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 429000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-46.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-47",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-47",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 452,019 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 452019,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-47.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-48",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-48",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 469,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 469000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-48.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-49",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-49",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 629,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 629000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-49.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  },
  {
    "id": "nk-auto-20260912-50",
    "adapterId": "owner-approved-automatic-marketplace",
    "sourceReference": "NK-AUTO-20260912-50",
    "title": "2019 Toyota Hilux Revo",
    "summary": "Toyota Hilux Revo ปี 2019 ราคาจากประกาศ 629,000 บาท สถานะรถและความพร้อมจำหน่ายยังไม่ได้รับการยืนยันจากผู้ขาย",
    "brand": "Toyota",
    "model": "Hilux Revo",
    "year": 2019,
    "grade": "Marketplace listing",
    "engine": "Unknown",
    "transmission": "Unknown",
    "drive": "Unknown",
    "body": "Pickup",
    "mileageKm": null,
    "color": "Unknown",
    "observedPriceThb": 629000,
    "observedAt": "2026-09-12T16:00:52.151Z",
    "generalLocation": "Bangkok",
    "imageUrls": [
      "/vehicle-marketplace/auto-published-20260912/car-50.jpg"
    ],
    "availability": "Availability Not Yet Confirmed",
    "translationState": "Normalized",
    "evidenceLabels": [
      "Facebook Marketplace listing",
      "1 customer-safe source photo",
      "Automatically published by Owner instruction"
    ],
    "demo": false
  }
];
