export type DemoInternalSourceRecord = {
  id: string; adapterId: string; sourceReference: string; sourcePlatform: string; sourceUrl: string; sellerName: string; sellerPhone: string; exactLocation: string; internalNotes: string;
  title: string; summary: string; brand: string; model: string; year: number; grade: string; engine: string; transmission: "AT" | "MT"; drive: "2WD" | "4WD"; body: string; mileageKm: number; color: string; observedPriceThb: number; observedAt: string; generalLocation: string; imageUrls: string[]; availability: "Availability Not Yet Confirmed"; translationState: "Normalized" | "Need Review"; evidenceLabels: string[]; demo: true;
};
const images = {
  revoWhite: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=82", rangerBlack: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1200&q=82", dmaxGrey: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=82", revoBlack: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=82", pickupSilver: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=82", pickupBlue: "https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=82", pickupRed: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=82", pickupWhite: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=82",
};
const observedAt = "2026-08-23T08:30:00.000Z";
export const demoInternalSourceRecords: DemoInternalSourceRecord[] = [
  { id:"th-demo-001",adapterId:"demo-thai-market",sourceReference:"DEMO-TH-001",sourcePlatform:"Demo partner feed",sourceUrl:"https://example.invalid/internal/demo-th-001",sellerName:"Siam Pickup Demo",sellerPhone:"+66 81 000 0101",exactLocation:"Bang Kapi, Bangkok",internalNotes:"Demo-only source. Current availability has not been contacted or confirmed.",title:"2023 Toyota Hilux Revo Rocco",summary:"Thai-market double-cab pickup normalized into English from listing evidence. Current availability and final condition are not yet verified.",brand:"Toyota",model:"Hilux Revo",year:2023,grade:"Rocco",engine:"2.4L diesel",transmission:"AT",drive:"2WD",body:"Double Cab",mileageKm:65454,color:"Dark Grey",observedPriceThb:765000,observedAt,generalLocation:"Bangkok",imageUrls:[images.revoBlack,images.revoWhite],availability:"Availability Not Yet Confirmed",translationState:"Normalized",evidenceLabels:["Listing title","Listing description","Odometer text"],demo:true },
  { id:"th-demo-002",adapterId:"demo-thai-market",sourceReference:"DEMO-TH-002",sourcePlatform:"Demo Thai vehicle website",sourceUrl:"https://example.invalid/internal/demo-th-002",sellerName:"Eastern Auto Demo",sellerPhone:"+66 89 000 0102",exactLocation:"Si Racha, Chon Buri",internalNotes:"Demo-only result. Price is observed, not verified.",title:"2021 Toyota Hilux Revo Z Edition",summary:"Smart-cab Thai-market pickup with automatic transmission. Facts shown are limited to the demo listing evidence.",brand:"Toyota",model:"Hilux Revo",year:2021,grade:"Z Edition",engine:"2.4L diesel",transmission:"AT",drive:"2WD",body:"Smart Cab",mileageKm:82100,color:"White",observedPriceThb:599000,observedAt,generalLocation:"Chon Buri",imageUrls:[images.revoWhite,images.pickupSilver],availability:"Availability Not Yet Confirmed",translationState:"Normalized",evidenceLabels:["Listing title","Listing description"],demo:true },
  { id:"th-demo-003",adapterId:"demo-thai-market",sourceReference:"DEMO-TH-003",sourcePlatform:"Demo dealer feed",sourceUrl:"https://example.invalid/internal/demo-th-003",sellerName:"Metro 4x4 Demo",sellerPhone:"+66 82 000 0103",exactLocation:"Lat Krabang, Bangkok",internalNotes:"Demo-only high-spec result. VIN evidence not supplied.",title:"2022 Toyota Hilux Revo GR Sport",summary:"Wide-body 4WD double cab with normalized English specification. VIN and live seller confirmation remain pending.",brand:"Toyota",model:"Hilux Revo",year:2022,grade:"GR Sport Wide",engine:"2.8L diesel",transmission:"AT",drive:"4WD",body:"Double Cab",mileageKm:31800,color:"Black",observedPriceThb:1190000,observedAt,generalLocation:"Bangkok",imageUrls:[images.revoBlack,images.rangerBlack],availability:"Availability Not Yet Confirmed",translationState:"Normalized",evidenceLabels:["Listing title","Badge photo","Odometer photo"],demo:true },
  { id:"th-demo-004",adapterId:"demo-thai-market",sourceReference:"DEMO-TH-004",sourcePlatform:"Demo partner feed",sourceUrl:"https://example.invalid/internal/demo-th-004",sellerName:"Isan Truck Demo",sellerPhone:"+66 86 000 0104",exactLocation:"Mueang, Khon Kaen",internalNotes:"Demo source awaiting current document evidence.",title:"2020 Isuzu D-Max V-Cross",summary:"Four-wheel-drive double cab normalized for an overseas buyer. Document and condition checks remain required.",brand:"Isuzu",model:"D-Max",year:2020,grade:"V-Cross",engine:"3.0L diesel",transmission:"AT",drive:"4WD",body:"Double Cab",mileageKm:74200,color:"Grey",observedPriceThb:815000,observedAt,generalLocation:"Khon Kaen",imageUrls:[images.dmaxGrey,images.pickupSilver],availability:"Availability Not Yet Confirmed",translationState:"Normalized",evidenceLabels:["Listing title","Listing text","Dashboard photo"],demo:true },
  { id:"th-demo-005",adapterId:"demo-thai-market",sourceReference:"DEMO-TH-005",sourcePlatform:"Demo Thai vehicle website",sourceUrl:"https://example.invalid/internal/demo-th-005",sellerName:"Northern Motors Demo",sellerPhone:"+66 95 000 0105",exactLocation:"Hang Dong, Chiang Mai",internalNotes:"Demo only. Seller response speed not measured.",title:"2021 Ford Ranger Wildtrak",summary:"Bi-turbo 4WD double cab with automatic transmission. Availability and inspection are still pending.",brand:"Ford",model:"Ranger",year:2021,grade:"Wildtrak",engine:"2.0L Bi-Turbo diesel",transmission:"AT",drive:"4WD",body:"Double Cab",mileageKm:55600,color:"Black",observedPriceThb:920000,observedAt,generalLocation:"Chiang Mai",imageUrls:[images.rangerBlack,images.pickupBlue],availability:"Availability Not Yet Confirmed",translationState:"Normalized",evidenceLabels:["Listing title","Listing description","Dashboard photo"],demo:true },
  { id:"th-demo-006",adapterId:"demo-thai-market",sourceReference:"DEMO-TH-006",sourcePlatform:"Demo dealer feed",sourceUrl:"https://example.invalid/internal/demo-th-006",sellerName:"Rayong Pickup Demo",sellerPhone:"+66 94 000 0106",exactLocation:"Pluak Daeng, Rayong",internalNotes:"Demo only. Service history was mentioned but no document image supplied.",title:"2020 Mitsubishi Triton GT Premium",summary:"4WD double cab with English-normalized listing facts. Service history and current condition need verification.",brand:"Mitsubishi",model:"Triton",year:2020,grade:"GT Premium",engine:"2.4L diesel",transmission:"AT",drive:"4WD",body:"Double Cab",mileageKm:89300,color:"Blue",observedPriceThb:675000,observedAt,generalLocation:"Rayong",imageUrls:[images.pickupBlue,images.pickupRed],availability:"Availability Not Yet Confirmed",translationState:"Need Review",evidenceLabels:["Listing title","Listing description"],demo:true },
  { id:"th-demo-007",adapterId:"demo-thai-market",sourceReference:"DEMO-TH-007",sourcePlatform:"Demo partner feed",sourceUrl:"https://example.invalid/internal/demo-th-007",sellerName:"Korat Auto Demo",sellerPhone:"+66 88 000 0107",exactLocation:"Pak Chong, Nakhon Ratchasima",internalNotes:"Demo only. Mileage requires instrument-cluster confirmation.",title:"2019 Nissan Navara VL",summary:"Four-wheel-drive double cab normalized from available text. Mileage evidence needs review before verification.",brand:"Nissan",model:"Navara",year:2019,grade:"VL",engine:"2.3L diesel",transmission:"AT",drive:"4WD",body:"Double Cab",mileageKm:103000,color:"Red",observedPriceThb:585000,observedAt,generalLocation:"Nakhon Ratchasima",imageUrls:[images.pickupRed,images.dmaxGrey],availability:"Availability Not Yet Confirmed",translationState:"Need Review",evidenceLabels:["Listing title","Listing description"],demo:true },
  { id:"th-demo-008",adapterId:"demo-thai-market",sourceReference:"DEMO-TH-008",sourcePlatform:"Demo Thai vehicle website",sourceUrl:"https://example.invalid/internal/demo-th-008",sellerName:"Ayutthaya Truck Demo",sellerPhone:"+66 92 000 0108",exactLocation:"Bang Pa-in, Ayutthaya",internalNotes:"Demo only. Older vehicle requires complete structural and document inspection.",title:"2014 Toyota Hilux Vigo Champ",summary:"Older 4WD double cab with automatic transmission. Structural, document, and mileage checks are required.",brand:"Toyota",model:"Hilux Vigo",year:2014,grade:"Champ G",engine:"3.0L diesel",transmission:"AT",drive:"4WD",body:"Double Cab",mileageKm:137000,color:"Silver",observedPriceThb:465000,observedAt,generalLocation:"Ayutthaya",imageUrls:[images.pickupSilver,images.pickupWhite],availability:"Availability Not Yet Confirmed",translationState:"Normalized",evidenceLabels:["Listing title","Listing description","Odometer text"],demo:true },
];
