export const SUPPORTED_LANGUAGES = Object.freeze(["en", "zh-CN", "th"]);

const dictionaries = {
  en: {
    language: "Language", english: "English", chinese: "简体中文", thai: "ไทย",
    browse: "Browse", saved: "Saved", myCases: "My Cases", inspections: "Inspections", messages: "Messages",
    vehiclePrice: "Vehicle Price", platformTransactionFee: "NK Platform & Transaction Fee", buyingServiceFee: "NK Buying Service",
    inspectionTravel: "Inspection & Travel", domesticTransport: "Domestic Transport", repairModification: "Repair / Modification",
    exportShipping: "Export / Shipping", otherAgreedCharges: "Other Agreed Charges", total: "Total", knownSubtotal: "Current total / subtotal",
    transparentPricing: "Transparent pricing", workingPriceStructure: "Working price structure", whatsIncluded: "What's included?",
    platformIncluded: "NK platform access, Vehicle Case, transaction workflow, document and workflow administration, case tracking, and system coordination.",
    buyingIncluded: "Thai seller communication, availability confirmation, seller verification, negotiation coordination, purchase coordination, and vehicle acquisition support.",
    nkServiceDisclosure: "These are NK Cars service fees. They are not charged by Facebook, Marketplace, the Thai government, or another third party.",
    finalPurchasePriceNote: "NK service amounts use the current vehicle price until the actual purchase price is confirmed. They recalculate from the actual vehicle purchase price.",
    pending: "Pending", known: "Known", pendingCosts: "{count} pending cost lines are excluded. This is not a final quote.",
    allCostsIncluded: "All current cost lines are included. Final approval is still required.",
    checkAvailability: "Check Availability", requestInspection: "Request Inspection", askNkAi: "Ask NK AI", saveToNk: "Save to NK", buyThroughNk: "Buy Through NK",
    browseVehicles: "Browse Vehicles", savedVehicles: "Saved Vehicles", searchVehicles: "Search vehicles", filters: "Filters", sort: "Sort",
    vehicleCriteria: "Vehicle criteria", location: "Thai search location", yearFrom: "Year from", yearTo: "Year to", minPrice: "Minimum price (USD)", maxPrice: "Maximum price (USD)", maxMileage: "Maximum mileage (km)", any: "Any", recommended: "Recommended", priceLow: "Price: low first", priceHigh: "Price: high first", newestYear: "Newest year", lowestMileage: "Lowest mileage", showVehicles: "Show {count} vehicles",
    vehicles: "vehicles", results: "results", pasteLink: "Paste link", noSaved: "No saved vehicles yet", noMatches: "No vehicles match these filters",
    resetFilters: "Reset filters", year: "Year", engine: "Engine", transmission: "Transmission", drive: "Drive", bodyCab: "Body / Cab", mileage: "Mileage",
    vehicleOverview: "Vehicle overview", vehicleSpecifications: "Vehicle specifications", continueThroughNk: "Continue through NK", chooseNext: "What would you like to do?",
    saveVehicle: "Save Vehicle", savedAction: "Saved", caseSummary: "Case summary", caseTimeline: "Case timeline", nkAiAssistant: "NK AI Assistant",
    inspectionNetwork: "Inspection network", conversationHistory: "Conversation history", account: "Account", sendQuestion: "Send question",
    askPlaceholder: "Ask about this vehicle, price, or inspection", sourceVehicle: "Source Vehicle", availability: "Availability", translation: "Translation",
    messagesTitle: "Messages", inspectionTitle: "Inspections", buy: "Buy", thailand: "Thailand", searchArea: "Search area",
    bangkokMetro: "Bangkok Metro", nearbyProvinces: "Nearby provinces", allThailand: "All Thailand",
    translatedVehicleDetails: "Translated vehicle details", translatedFromThai: "Translated from Thai", needsReview: "Needs review",
    originalFactsPreserved: "Original listing facts are preserved separately. Unknown details still require NK verification.", listingFacts: "Listing facts", sourcePhotos: "{count} source photos",
    recommendedFirstStep: "Recommended first step", inspectionInsideCase: "Managed inside your Vehicle Case", continueExistingCase: "Continue in your existing Vehicle Case", createCaseNoCommitment: "Start a Vehicle Case with no purchase commitment",
    inventoryStorage: "NK inventory storage", synchronized: "Synchronized", fallbackActive: "Fallback active",
    inventoryGroundingLive: "Results use Owner-approved records and customer-safe media from NK's QNAP storage.",
    inventoryGroundingFallback: "QNAP synchronization is unavailable. Results use the last verified NK snapshot and never invent current availability.",
    inventoryPrivacy: "Only Owner-approved customer-safe records and media are shown here. Source URLs, seller details, and internal storage references stay private.",
    customerWorkspace: "Customer workspace", noCasesTitle: "No Vehicle Cases yet", noCasesText: "Save a vehicle result as a case to start availability, pricing, inspection, and conversation history.", caseCount: "{count} cases",
    inspectionLocationPending: "Inspection location pending", inspectionQuoteReady: "Inspection quote ready", inspectionAwaitingProvider: "Waiting for inspection provider", loadingVehicleCase: "Loading Vehicle Case...", caseNotFound: "Vehicle Case not found", caseNotFoundText: "This case may have been reset or belongs to a different account.", backToCases: "Back to My Cases",
    currentFacts: "Current facts", priceObserved: "Price observed", lastCaseUpdate: "Last case update", customerPrivacyNote: "Seller contact, source URL, internal notes, source identity, and internal margin are never exposed in this customer case.",
    auditHistory: "Audit-friendly history", oneCustomerAssistant: "One customer assistant", groundedPreview: "Grounded preview", aiBoundary: "This preview uses deterministic grounded replies. It does not send seller messages or call an external AI service.",
    travelZone: "Travel zone", openCase: "Open Case", aiVehicleSearch: "NK AI vehicle search", generalRequirements: "General requirements before a Vehicle Case is selected.", continueConversation: "Continue search conversation", noConversations: "No case conversations yet", noConversationsText: "Create a Vehicle Case and ask NK AI or request availability.",
    nkCustomerAccount: "NK customer account", accountIntro: "Customer identity and destination details remain separate from the Thai vehicle search location.", localPreviewIdentity: "Local device identity", customerCountry: "Customer country", destinationPort: "Destination port", vehicleSearchArea: "Vehicle search area", vehicleInventory: "Vehicle inventory", openSourceBrowser: "Open source app/browser",
    thisDevice: "This device", secureAccountData: "Secure account data", vehicleCases: "Vehicle Cases", inspectionRequests: "Inspection requests", signInSync: "Sign in to sync Vehicle Cases", accountSignInUnavailable: "Secure account sign-in is awaiting activation. Your current workspace remains on this device.", resetWorkspacePrompt: "Remove saved vehicles, Vehicle Cases, and conversation history from this workspace?", cancel: "Cancel", clearWorkspaceData: "Clear workspace data", resetDeviceData: "Reset device data", resetAccountData: "Reset account data", anonymousDataNote: "Anonymous activity stays on this device. Sign in before creating business-critical Vehicle Cases.", syncedDataNote: "Vehicle Cases and conversation history are stored in an account-isolated server workspace with revision checks and append-only sync events.", syncing: "Syncing", deviceLocal: "Device local", workspaceSynced: "Saved vehicles, Vehicle Cases, and history are synchronized to this account.", workspaceSyncing: "Synchronizing this workspace...", workspaceDeviceLocal: "This workspace is stored only on this device until account sign-in is available.",
    vehicleNotFound: "Vehicle result not found", vehicleNotFoundText: "This vehicle result is no longer in the reviewed set.", backToBrowse: "Back to Browse", nkSelection: "NK Selection", observedPriceCaption: "Observed asking price at {date}. {fx} Current price is not yet verified.", generalVehicleLocation: "General vehicle location", sourceVehicleDisclosure: "This is a source vehicle, not NK-owned stock. Seller identity and source link remain internal.", photoCounter: "{current} of {total}", openPhoto: "Open photo {number} fullscreen", previousPhoto: "Previous photo", nextPhoto: "Next photo", closeGallery: "Close fullscreen gallery",
    groundedVehicleSearch: "Grounded vehicle search", customerSafeMatches: "Customer-safe matches", resultCount: "{count} results", noApprovedMatch: "No current approved match", useFullFilters: "Use full filters", noApprovedMatchText: "No approved staged vehicle matches this request. The request was recorded and no result was invented.",
    secureSource: "Secure source", browseRealMarketplace: "Browse the real Marketplace", facebookSessionNotice: "Facebook opens using your own account and session. NK cannot read your password, cookies, MFA, CAPTCHA, searches, or other Facebook activity.", openFacebookMarketplace: "Open Facebook Marketplace", marketplaceTabOpened: "Marketplace tab opened", readyToBrowse: "Ready to browse", marketplaceOpenedHelp: "Search normally, open a vehicle, then Copy Link or Share back to NK.", facebookExternalHelp: "Facebook remains outside the web app because Facebook blocks embedded web pages.", pasteFacebookLink: "Paste Facebook vehicle link", pasteVehicleLink: "Paste vehicle link from clipboard", translateAction: "Translate", checkCar: "Check Car", backToNk: "Back to NK Cars", reloadMarketplace: "Reload Facebook Marketplace", nkVehicleActions: "NK vehicle actions",
    facebookOpenedMessage: "Facebook opened in its own secure tab. Return here after copying or sharing the vehicle link.", invalidClipboardLink: "Clipboard does not contain a valid HTTPS Facebook vehicle link.", linkDetected: "Vehicle link detected. Save it to NK when ready.", clipboardUnavailable: "Clipboard access is unavailable. Paste the vehicle link into the address field.", validLinkFirst: "Paste a valid HTTPS Facebook vehicle link first.", chooseVehicleFirst: "Open a vehicle in Facebook, copy its link, then return and paste it here.",
    realMarketplaceFlow: "Real Marketplace buying flow", browseFacebookSaveNk: "Browse Facebook. Save the vehicle to NK.", sourceShareIntro: "Use your own Facebook account and normal Marketplace search. NK receives only the vehicle you choose to share.", facebookSessionStays: "Your Facebook session stays with Facebook", noFacebookCredentials: "NK does not collect your Facebook password, MFA response, CAPTCHA, or browser cookies.", stepSearchMarketplace: "Search and filter normally in Facebook Marketplace", stepOpenShare: "Open a vehicle and tap Share", stepChooseSaveNk: "Choose Save to NK Cars when available", shareExtensionNotice: "On supported installed NK apps, sharing opens NK and creates the Vehicle Case automatically. iPhone requires the NK iOS Share Extension; the web app cannot install that extension.", webAppCompanion: "Web app companion", tryNkWebBrowser: "Try the NK Web Browser", webBrowserIntro: "Open the real Facebook Marketplace, then return with the selected vehicle link to use NK actions and create a Vehicle Case.", openNkWebBrowser: "Open NK Web Browser", otherNkPaths: "Other NK paths", continueInsideNk: "Continue inside NK", browseSavedResults: "Browse saved NK results", lastResortPaste: "Last resort: paste a link",
    saveToNkCars: "Save to NK Cars", lastResortFallback: "Last-resort link fallback", creatingVehicleCase: "Creating your Vehicle Case", pasteFacebookVehicleLink: "Paste a Facebook Vehicle Link", importingSharedVehicle: "NK is importing the vehicle you shared and will open its case automatically.", fallbackOnlyNotice: "Use this only when Save to NK Cars is unavailable on your device.", browseInFacebook: "Browse in Facebook Marketplace", facebookLoginControl: "Facebook opens outside NK and keeps your login, MFA, and session under Facebook control.", stepBrowseSelect: "Browse and select a real vehicle", stepShareCopy: "Use Share or Copy Link", stepReturnPaste: "Return here and paste the link", vehicleListingUrl: "Vehicle listing URL", pasteAction: "Paste", importAnalyze: "Import & Analyze", sourceSafety: "NK stores only the selected listing link and accessible evidence. NK does not collect Facebook passwords, copy session cookies, or bypass MFA/CAPTCHA.", openSourceListing: "Open source listing", vehiclePhotoPending: "Vehicle photo pending", accessibleImages: "{count} accessible images", importedPreview: "Customer-safe imported preview", workingFallback: "Working fallback", uploadScreenshotsPhotos: "Upload Screenshots / Photos", uploadThirty: "Select up to 30 images from one vehicle. They are analyzed together, not as unrelated vehicles.", addMoreImages: "Add more images", choosePhotos: "Choose screenshots / photos", selectedCount: "{count}/30 selected - iPhone and Android compatible", listingTextLabel: "Listing text", listingTextPlaceholder: "Paste the vehicle title, description, price, mileage, and specifications here.", saveManualReview: "Save for manual review", analyzeNkAi: "Analyze with NK AI", localEvidenceNotice: "Uploaded evidence remains on this device until private durable media storage and authenticated case ownership are connected.", backBrowseVehicles: "Back to Browse Vehicles",
    clipboardNoFacebookLink: "The clipboard does not contain a Facebook vehicle link.", facebookLinkPasted: "Facebook link pasted. Import it when ready.", clipboardPasteManual: "Clipboard access is unavailable. Paste the Facebook link into the field manually.", completeHttpsLink: "Paste a complete HTTPS vehicle link.", noConnectedImporter: "This source does not have a connected importer yet. The link is preserved; add screenshots/photos or listing text below.", listingUnreadable: "This listing could not be read automatically. Continue with screenshots/photos or listing text.", partialImport: "Only part of the listing was accessible. Review the facts and add screenshots/photos for missing evidence.", accessibleImported: "Accessible listing evidence imported. Availability is still not confirmed.", sourceUnreachable: "The source could not be reached from this session. Continue with screenshots/photos or listing text.", imagePrepFailed: "One or more selected images could not be prepared. Try another photo or screenshot.", aiNotConnected: "NK AI is not connected. You can still save an evidence case for manual review.", aiAnalyzeFailed: "NK AI could not analyze this evidence. You can still save it for manual review.", aiAnalyzed: "NK AI analyzed the uploaded evidence as one vehicle. Review unknown or low-confidence facts before verification.", aiUnreachable: "NK AI could not be reached. You can still save an evidence case for manual review.", evidencePrepared: "Evidence case prepared. Specifications, source price, and availability remain unconfirmed.",
    buyingBrowser: "Buying Browser", homeLabel: "NK Cars Buying Browser home", navLabel: "Buying Browser navigation", mobileNavLabel: "Buying Browser mobile navigation", openAccount: "Open account", deviceAccount: "Device account", nkAccount: "NK account", removeSaved: "Remove {vehicle} from saved vehicles", removeSavedVehicle: "Remove saved vehicle",
  },
  "zh-CN": {
    language: "语言", english: "English", chinese: "简体中文", thai: "ไทย",
    browse: "浏览", saved: "已保存", myCases: "我的案件", inspections: "验车", messages: "消息",
    vehiclePrice: "车辆价格", platformTransactionFee: "NK 平台及交易服务费", buyingServiceFee: "NK 购车服务费",
    inspectionTravel: "验车及出行费用", domesticTransport: "泰国内陆运输", repairModification: "维修 / 改装",
    exportShipping: "出口 / 海运费用", otherAgreedCharges: "其他约定费用", total: "总计", knownSubtotal: "当前总计 / 小计",
    transparentPricing: "透明价格", workingPriceStructure: "当前价格明细", whatsIncluded: "包含哪些服务？",
    platformIncluded: "包括 NK 平台使用、车辆案件、交易流程、文件与流程管理、案件跟踪和系统协调。",
    buyingIncluded: "包括与泰国卖家沟通、确认可售状态、卖家核实、议价协调、购买协调和车辆采购支持。",
    nkServiceDisclosure: "这些是 NK Cars 的服务费用，并非 Facebook、Marketplace、泰国政府或其他第三方收取。",
    finalPurchasePriceNote: "在实际购买价格确认前，NK 服务金额按当前车辆价格计算；确认后将按实际购买价格重新计算。",
    pending: "待确认", known: "已确认", pendingCosts: "{count} 项待确认费用未计入。这不是最终报价。",
    allCostsIncluded: "当前费用均已计入，最终仍需批准。",
    checkAvailability: "确认车辆是否可售", requestInspection: "申请验车", askNkAi: "询问 NK AI", saveToNk: "保存到 NK", buyThroughNk: "通过 NK 购买",
    browseVehicles: "浏览车辆", savedVehicles: "已保存车辆", searchVehicles: "搜索车辆", filters: "筛选", sort: "排序",
    vehicleCriteria: "车辆条件", location: "泰国搜索地区", yearFrom: "起始年份", yearTo: "截止年份", minPrice: "最低价格（USD）", maxPrice: "最高价格（USD）", maxMileage: "最高里程（km）", any: "不限", recommended: "推荐", priceLow: "价格从低到高", priceHigh: "价格从高到低", newestYear: "年份最新", lowestMileage: "里程最低", showVehicles: "显示 {count} 辆车",
    vehicles: "辆车", results: "个结果", pasteLink: "粘贴链接", noSaved: "尚未保存车辆", noMatches: "没有符合筛选条件的车辆",
    resetFilters: "重置筛选", year: "年份", engine: "发动机", transmission: "变速箱", drive: "驱动", bodyCab: "车身 / 驾驶室", mileage: "里程",
    vehicleOverview: "车辆概览", vehicleSpecifications: "车辆规格", continueThroughNk: "继续通过 NK", chooseNext: "您下一步想做什么？",
    saveVehicle: "保存车辆", savedAction: "已保存", caseSummary: "案件摘要", caseTimeline: "案件时间线", nkAiAssistant: "NK AI 助手",
    inspectionNetwork: "验车服务", conversationHistory: "对话记录", account: "账户", sendQuestion: "发送问题",
    askPlaceholder: "询问车辆、价格或验车信息", sourceVehicle: "来源车辆", availability: "可售状态", translation: "翻译",
    messagesTitle: "消息", inspectionTitle: "验车", buy: "购买", thailand: "泰国", searchArea: "搜索区域",
    bangkokMetro: "曼谷及周边地区", nearbyProvinces: "邻近府", allThailand: "全泰国",
    translatedVehicleDetails: "已翻译的车辆信息", translatedFromThai: "从泰语翻译", needsReview: "需要审核",
    originalFactsPreserved: "原始车源信息会单独保留。未知信息仍需 NK 核实。", listingFacts: "车源信息", sourcePhotos: "{count} 张车源照片",
    recommendedFirstStep: "建议的第一步", inspectionInsideCase: "在车辆案件中管理", continueExistingCase: "继续现有车辆案件", createCaseNoCommitment: "创建车辆案件，无购买承诺",
    inventoryStorage: "NK 车辆数据存储", synchronized: "已同步", fallbackActive: "正在使用备用数据",
    inventoryGroundingLive: "结果来自 NK QNAP 存储中经车主批准的记录和客户可见媒体。",
    inventoryGroundingFallback: "QNAP 同步当前不可用。结果使用 NK 最近验证的快照，不会虚构当前可售状态。",
    inventoryPrivacy: "这里只显示经车主批准的客户可见记录和媒体。车源链接、卖家信息和内部存储引用保持私密。",
    customerWorkspace: "客户工作区", noCasesTitle: "暂无车辆案件", noCasesText: "保存车辆并创建案件，即可开始确认可售状态、价格、验车和对话记录。", caseCount: "{count} 个案件",
    inspectionLocationPending: "验车地点待确认", inspectionQuoteReady: "验车报价已准备", inspectionAwaitingProvider: "等待验车服务商", loadingVehicleCase: "正在加载车辆案件...", caseNotFound: "未找到车辆案件", caseNotFoundText: "此案件可能已重置或属于其他账户。", backToCases: "返回我的案件",
    currentFacts: "当前信息", priceObserved: "价格记录时间", lastCaseUpdate: "案件最近更新", customerPrivacyNote: "此客户案件绝不会显示卖家联系方式、车源链接、内部备注、车源身份或内部利润。",
    auditHistory: "可审计记录", oneCustomerAssistant: "统一客户助手", groundedPreview: "基于记录的预览", aiBoundary: "此预览使用基于案件记录的确定性回复，不会向卖家发送消息，也不会调用外部 AI 服务。",
    travelZone: "出行区域", openCase: "打开案件", aiVehicleSearch: "NK AI 车辆搜索", generalRequirements: "选择车辆案件前的一般需求。", continueConversation: "继续搜索对话", noConversations: "暂无案件对话", noConversationsText: "创建车辆案件后，可询问 NK AI 或申请确认可售状态。",
    nkCustomerAccount: "NK 客户账户", accountIntro: "客户身份和目的地信息与泰国车辆搜索地区分开管理。", localPreviewIdentity: "本机身份", customerCountry: "客户国家", destinationPort: "目的港", vehicleSearchArea: "车辆搜索地区", vehicleInventory: "车辆库存", openSourceBrowser: "打开车源应用 / 浏览器",
    thisDevice: "此设备", secureAccountData: "安全账户数据", vehicleCases: "车辆案件", inspectionRequests: "验车申请", signInSync: "登录并同步车辆案件", accountSignInUnavailable: "安全账户登录正在等待启用。当前工作区仍保存在此设备。", resetWorkspacePrompt: "是否移除此工作区中的已保存车辆、车辆案件和对话记录？", cancel: "取消", clearWorkspaceData: "清除工作区数据", resetDeviceData: "重置设备数据", resetAccountData: "重置账户数据", anonymousDataNote: "匿名活动仅保存在此设备。创建重要业务案件前请先登录。", syncedDataNote: "车辆案件和对话记录存储在账户隔离的服务器工作区，并使用版本检查和只追加同步事件。", syncing: "同步中", deviceLocal: "仅本机", workspaceSynced: "已保存车辆、车辆案件和历史记录已同步到此账户。", workspaceSyncing: "正在同步此工作区...", workspaceDeviceLocal: "在账户登录可用前，此工作区仅保存在本设备。",
    vehicleNotFound: "未找到车辆", vehicleNotFoundText: "此车辆已不在审核通过的列表中。", backToBrowse: "返回浏览", nkSelection: "NK 精选", observedPriceCaption: "观察到的报价时间：{date}。{fx} 当前价格尚未核实。", generalVehicleLocation: "车辆大致位置", sourceVehicleDisclosure: "这是车源车辆，并非 NK 自有库存。卖家身份和车源链接仅供内部使用。", photoCounter: "{current} / {total}", openPhoto: "全屏打开第 {number} 张照片", previousPhoto: "上一张", nextPhoto: "下一张", closeGallery: "关闭全屏相册",
    groundedVehicleSearch: "基于记录的车辆搜索", customerSafeMatches: "客户可见匹配", resultCount: "{count} 个结果", noApprovedMatch: "暂无审核通过的匹配", useFullFilters: "使用完整筛选", noApprovedMatchText: "没有审核通过的暂存车辆符合此需求。系统已记录需求，未虚构结果。",
    secureSource: "安全车源", browseRealMarketplace: "浏览真实 Marketplace", facebookSessionNotice: "Facebook 使用您自己的账户和会话打开。NK 无法读取您的密码、Cookie、MFA、CAPTCHA、搜索或其他 Facebook 活动。", openFacebookMarketplace: "打开 Facebook Marketplace", marketplaceTabOpened: "Marketplace 标签页已打开", readyToBrowse: "可以开始浏览", marketplaceOpenedHelp: "正常搜索并打开车辆，然后复制链接或分享回 NK。", facebookExternalHelp: "由于 Facebook 阻止嵌入网页，Facebook 会在 NK 网页应用外打开。", pasteFacebookLink: "粘贴 Facebook 车辆链接", pasteVehicleLink: "从剪贴板粘贴车辆链接", translateAction: "翻译", checkCar: "检查车辆", backToNk: "返回 NK Cars", reloadMarketplace: "重新打开 Facebook Marketplace", nkVehicleActions: "NK 车辆操作",
    facebookOpenedMessage: "Facebook 已在独立安全标签页中打开。复制或分享车辆链接后请返回此处。", invalidClipboardLink: "剪贴板中没有有效的 HTTPS Facebook 车辆链接。", linkDetected: "已检测到车辆链接，准备好后可保存到 NK。", clipboardUnavailable: "无法访问剪贴板，请将车辆链接粘贴到地址栏。", validLinkFirst: "请先粘贴有效的 HTTPS Facebook 车辆链接。", chooseVehicleFirst: "请在 Facebook 打开车辆、复制链接，然后返回并粘贴到此处。",
    realMarketplaceFlow: "真实 Marketplace 购车流程", browseFacebookSaveNk: "浏览 Facebook，将车辆保存到 NK。", sourceShareIntro: "使用您自己的 Facebook 账户正常搜索 Marketplace。NK 只接收您主动分享的车辆。", facebookSessionStays: "您的 Facebook 会话保留在 Facebook", noFacebookCredentials: "NK 不会收集您的 Facebook 密码、MFA 回应、CAPTCHA 或浏览器 Cookie。", stepSearchMarketplace: "在 Facebook Marketplace 正常搜索和筛选", stepOpenShare: "打开车辆并点击分享", stepChooseSaveNk: "可用时选择保存到 NK Cars", shareExtensionNotice: "在支持的 NK 应用中，分享会打开 NK 并自动创建车辆案件。iPhone 需要 NK iOS 分享扩展，网页应用无法安装该扩展。", webAppCompanion: "网页应用助手", tryNkWebBrowser: "试用 NK 网页浏览器", webBrowserIntro: "打开真实 Facebook Marketplace，选择车辆后带链接返回 NK，即可使用 NK 操作并创建车辆案件。", openNkWebBrowser: "打开 NK 网页浏览器", otherNkPaths: "其他 NK 入口", continueInsideNk: "在 NK 内继续", browseSavedResults: "浏览已保存的 NK 结果", lastResortPaste: "备用方式：粘贴链接",
    saveToNkCars: "保存到 NK Cars", lastResortFallback: "备用链接导入", creatingVehicleCase: "正在创建车辆案件", pasteFacebookVehicleLink: "粘贴 Facebook 车辆链接", importingSharedVehicle: "NK 正在导入您分享的车辆，并会自动打开其案件。", fallbackOnlyNotice: "仅在您的设备无法使用保存到 NK Cars 时使用此方式。", browseInFacebook: "在 Facebook Marketplace 浏览", facebookLoginControl: "Facebook 在 NK 外打开，登录、MFA 和会话均由 Facebook 管理。", stepBrowseSelect: "浏览并选择真实车辆", stepShareCopy: "使用分享或复制链接", stepReturnPaste: "返回此处并粘贴链接", vehicleListingUrl: "车辆链接", pasteAction: "粘贴", importAnalyze: "导入并分析", sourceSafety: "NK 只保存您选择的车源链接和可访问证据，不收集 Facebook 密码、不复制会话 Cookie，也不绕过 MFA/CAPTCHA。", openSourceListing: "打开车源页面", vehiclePhotoPending: "车辆照片待补充", accessibleImages: "可访问图片 {count} 张", importedPreview: "客户安全导入预览", workingFallback: "可用的备用方式", uploadScreenshotsPhotos: "上传截图 / 照片", uploadThirty: "可为同一车辆选择最多 30 张图片，系统会作为一辆车整体分析。", addMoreImages: "添加更多图片", choosePhotos: "选择截图 / 照片", selectedCount: "已选择 {count}/30 - 支持 iPhone 和 Android", listingTextLabel: "车源文字", listingTextPlaceholder: "粘贴车辆标题、描述、价格、里程和规格。", saveManualReview: "保存并人工审核", analyzeNkAi: "使用 NK AI 分析", localEvidenceNotice: "在私密持久媒体存储和账户案件连接前，上传证据仅保存在此设备。", backBrowseVehicles: "返回浏览车辆",
    clipboardNoFacebookLink: "剪贴板中没有 Facebook 车辆链接。", facebookLinkPasted: "已粘贴 Facebook 链接，准备好后可导入。", clipboardPasteManual: "无法访问剪贴板，请手动粘贴 Facebook 链接。", completeHttpsLink: "请粘贴完整的 HTTPS 车辆链接。", noConnectedImporter: "此车源尚未连接导入器。链接已保留，请在下方添加截图、照片或车源文字。", listingUnreadable: "无法自动读取此车源，请继续添加截图、照片或车源文字。", partialImport: "只能访问部分车源信息，请检查已知内容并补充截图或照片。", accessibleImported: "已导入可访问的车源证据，可售状态仍未确认。", sourceUnreachable: "当前会话无法访问车源，请继续添加截图、照片或车源文字。", imagePrepFailed: "无法处理部分图片，请尝试其他照片或截图。", aiNotConnected: "NK AI 尚未连接，仍可保存证据案件供人工审核。", aiAnalyzeFailed: "NK AI 无法分析此证据，仍可保存供人工审核。", aiAnalyzed: "NK AI 已将上传证据作为一辆车整体分析。核实前请检查未知或低置信度信息。", aiUnreachable: "无法连接 NK AI，仍可保存证据案件供人工审核。", evidencePrepared: "证据案件已准备，规格、车源价格和可售状态仍未确认。",
    buyingBrowser: "购车浏览器", homeLabel: "NK Cars 购车浏览器首页", navLabel: "购车浏览器导航", mobileNavLabel: "购车浏览器移动导航", openAccount: "打开账户", deviceAccount: "设备账户", nkAccount: "NK 账户", removeSaved: "从已保存车辆中移除 {vehicle}", removeSavedVehicle: "移除已保存车辆",
  },
  th: {
    language: "ภาษา", english: "English", chinese: "简体中文", thai: "ไทย",
    browse: "ค้นหารถ", saved: "บันทึกแล้ว", myCases: "เคสของฉัน", inspections: "ตรวจสภาพ", messages: "ข้อความ",
    vehiclePrice: "ราคารถ", platformTransactionFee: "ค่าบริการแพลตฟอร์มและธุรกรรม NK", buyingServiceFee: "ค่าบริการจัดซื้อรถ NK",
    inspectionTravel: "ค่าตรวจรถและเดินทาง", domesticTransport: "ค่าขนส่งภายในประเทศไทย", repairModification: "ค่าซ่อม / ดัดแปลง",
    exportShipping: "ค่าขนส่งออก / ค่าระวาง", otherAgreedCharges: "ค่าใช้จ่ายอื่นที่ตกลงกัน", total: "ยอดรวม", knownSubtotal: "ยอดรวม / ยอดย่อยปัจจุบัน",
    transparentPricing: "โครงสร้างราคาโปร่งใส", workingPriceStructure: "รายละเอียดราคาปัจจุบัน", whatsIncluded: "รวมบริการอะไรบ้าง?",
    platformIncluded: "การใช้แพลตฟอร์ม NK, Vehicle Case, ขั้นตอนธุรกรรม, การจัดการเอกสารและงาน, การติดตามเคส และการประสานงานระบบ",
    buyingIncluded: "การสื่อสารกับผู้ขายไทย, ยืนยันว่ารถยังอยู่, ตรวจสอบผู้ขาย, ประสานการต่อรอง, ประสานการซื้อ และช่วยดำเนินการจัดซื้อรถ",
    nkServiceDisclosure: "ค่าบริการเหล่านี้เป็นของ NK Cars ไม่ใช่ค่าธรรมเนียมจาก Facebook, Marketplace, รัฐบาลไทย หรือบุคคลภายนอก",
    finalPurchasePriceNote: "ก่อนยืนยันราคาซื้อจริง ระบบใช้ราคารถปัจจุบันคำนวณค่าบริการ และจะคำนวณใหม่จากราคาซื้อรถจริงเมื่อยืนยันแล้ว",
    pending: "รอยืนยัน", known: "ยืนยันแล้ว", pendingCosts: "ยังไม่รวมค่าใช้จ่ายที่รอยืนยัน {count} รายการ และยังไม่ใช่ใบเสนอราคาสุดท้าย",
    allCostsIncluded: "รวมค่าใช้จ่ายปัจจุบันครบแล้ว แต่ยังต้องได้รับการอนุมัติขั้นสุดท้าย",
    checkAvailability: "ตรวจสอบว่ารถยังอยู่หรือไม่", requestInspection: "ขอตรวจสภาพรถ", askNkAi: "ถาม NK AI", saveToNk: "บันทึกเข้า NK", buyThroughNk: "ซื้อผ่าน NK",
    browseVehicles: "ค้นหารถ", savedVehicles: "รถที่บันทึกไว้", searchVehicles: "ค้นหารถ", filters: "ตัวกรอง", sort: "เรียงลำดับ",
    vehicleCriteria: "เงื่อนไขรถ", location: "พื้นที่ค้นหาในประเทศไทย", yearFrom: "ปีเริ่มต้น", yearTo: "ปีสิ้นสุด", minPrice: "ราคาต่ำสุด (USD)", maxPrice: "ราคาสูงสุด (USD)", maxMileage: "เลขไมล์สูงสุด (km)", any: "ทั้งหมด", recommended: "แนะนำ", priceLow: "ราคาต่ำไปสูง", priceHigh: "ราคาสูงไปต่ำ", newestYear: "ปีใหม่ที่สุด", lowestMileage: "เลขไมล์ต่ำที่สุด", showVehicles: "แสดงรถ {count} คัน",
    vehicles: "คัน", results: "ผลลัพธ์", pasteLink: "วางลิงก์", noSaved: "ยังไม่มีรถที่บันทึก", noMatches: "ไม่พบรถตามตัวกรอง",
    resetFilters: "ล้างตัวกรอง", year: "ปี", engine: "เครื่องยนต์", transmission: "เกียร์", drive: "ระบบขับเคลื่อน", bodyCab: "ตัวถัง / ห้องโดยสาร", mileage: "เลขไมล์",
    vehicleOverview: "ภาพรวมรถ", vehicleSpecifications: "ข้อมูลรถ", continueThroughNk: "ดำเนินการผ่าน NK", chooseNext: "ต้องการทำอะไรต่อ?",
    saveVehicle: "บันทึกรถ", savedAction: "บันทึกแล้ว", caseSummary: "สรุปเคส", caseTimeline: "ลำดับเหตุการณ์", nkAiAssistant: "ผู้ช่วย NK AI",
    inspectionNetwork: "เครือข่ายตรวจสภาพ", conversationHistory: "ประวัติการสนทนา", account: "บัญชี", sendQuestion: "ส่งคำถาม",
    askPlaceholder: "ถามเกี่ยวกับรถ ราคา หรือการตรวจสภาพ", sourceVehicle: "รถจากแหล่งภายนอก", availability: "สถานะรถ", translation: "การแปล",
    messagesTitle: "ข้อความ", inspectionTitle: "ตรวจสภาพ", buy: "ซื้อ", thailand: "ประเทศไทย", searchArea: "พื้นที่ค้นหา",
    bangkokMetro: "กรุงเทพและปริมณฑล", nearbyProvinces: "จังหวัดใกล้เคียง", allThailand: "ทั่วประเทศไทย",
    translatedVehicleDetails: "ข้อมูลรถที่แปลแล้ว", translatedFromThai: "แปลจากภาษาไทย", needsReview: "ต้องตรวจสอบ",
    originalFactsPreserved: "ระบบเก็บข้อมูลต้นฉบับแยกไว้ รายละเอียดที่ยังไม่ทราบต้องให้ NK ตรวจสอบ", listingFacts: "ข้อมูลจากประกาศ", sourcePhotos: "รูปจากแหล่งข้อมูล {count} รูป",
    recommendedFirstStep: "ขั้นตอนแรกที่แนะนำ", inspectionInsideCase: "จัดการภายใน Vehicle Case", continueExistingCase: "ดำเนินการต่อใน Vehicle Case เดิม", createCaseNoCommitment: "เริ่ม Vehicle Case โดยยังไม่ผูกมัดการซื้อ",
    inventoryStorage: "พื้นที่เก็บข้อมูลรถ NK", synchronized: "ซิงก์แล้ว", fallbackActive: "กำลังใช้ข้อมูลสำรอง",
    inventoryGroundingLive: "ผลลัพธ์ใช้ข้อมูลที่ Owner อนุมัติและสื่อลูกค้าที่ปลอดภัยจากพื้นที่เก็บข้อมูล QNAP ของ NK",
    inventoryGroundingFallback: "ขณะนี้ซิงก์ QNAP ไม่ได้ ระบบใช้ snapshot ล่าสุดที่ NK ตรวจสอบแล้วและจะไม่แต่งสถานะรถขึ้นเอง",
    inventoryPrivacy: "หน้านี้แสดงเฉพาะข้อมูลและสื่อที่ Owner อนุมัติให้ลูกค้าเห็น ลิงก์ต้นทาง ข้อมูลผู้ขาย และตำแหน่งจัดเก็บภายในยังเป็นข้อมูลส่วนตัว",
    customerWorkspace: "พื้นที่ทำงานลูกค้า", noCasesTitle: "ยังไม่มี Vehicle Case", noCasesText: "บันทึกรถเป็นเคสเพื่อเริ่มตรวจสอบสถานะ ราคา การตรวจสภาพ และประวัติการสนทนา", caseCount: "{count} เคส",
    inspectionLocationPending: "รอยืนยันพื้นที่ตรวจสภาพ", inspectionQuoteReady: "ราคาตรวจสภาพพร้อมแล้ว", inspectionAwaitingProvider: "รอผู้ให้บริการตรวจสภาพ", loadingVehicleCase: "กำลังโหลด Vehicle Case...", caseNotFound: "ไม่พบ Vehicle Case", caseNotFoundText: "เคสนี้อาจถูกล้างหรือเป็นของบัญชีอื่น", backToCases: "กลับไปเคสของฉัน",
    currentFacts: "ข้อมูลปัจจุบัน", priceObserved: "เวลาที่พบราคา", lastCaseUpdate: "อัปเดตเคสล่าสุด", customerPrivacyNote: "เคสลูกค้าจะไม่แสดงข้อมูลติดต่อผู้ขาย ลิงก์ต้นทาง บันทึกภายใน ตัวตนแหล่งรถ หรือกำไรภายใน",
    auditHistory: "ประวัติที่ตรวจสอบได้", oneCustomerAssistant: "ผู้ช่วยลูกค้าหนึ่งเดียว", groundedPreview: "ตัวอย่างที่อ้างอิงข้อมูลจริง", aiBoundary: "ตัวอย่างนี้ตอบตามข้อมูลในเคสแบบกำหนดชัดเจน ไม่ได้ส่งข้อความหาผู้ขายหรือเรียกใช้บริการ AI ภายนอก",
    travelZone: "เขตการเดินทาง", openCase: "เปิดเคส", aiVehicleSearch: "ค้นหารถด้วย NK AI", generalRequirements: "ความต้องการทั่วไปก่อนเลือกรถเป็น Vehicle Case", continueConversation: "สนทนาค้นหาต่อ", noConversations: "ยังไม่มีการสนทนาในเคส", noConversationsText: "สร้าง Vehicle Case แล้วถาม NK AI หรือขอตรวจสอบสถานะรถ",
    nkCustomerAccount: "บัญชีลูกค้า NK", accountIntro: "ข้อมูลตัวตนและปลายทางของลูกค้าแยกจากพื้นที่ค้นหารถในประเทศไทย", localPreviewIdentity: "ข้อมูลบนอุปกรณ์นี้", customerCountry: "ประเทศลูกค้า", destinationPort: "ท่าเรือปลายทาง", vehicleSearchArea: "พื้นที่ค้นหารถ", vehicleInventory: "ข้อมูลรถ", openSourceBrowser: "เปิดแอป / เบราว์เซอร์ต้นทาง",
    thisDevice: "อุปกรณ์นี้", secureAccountData: "ข้อมูลบัญชีที่ปลอดภัย", vehicleCases: "Vehicle Case", inspectionRequests: "คำขอตรวจสภาพ", signInSync: "เข้าสู่ระบบเพื่อซิงก์ Vehicle Case", accountSignInUnavailable: "ระบบเข้าสู่บัญชีที่ปลอดภัยกำลังรอเปิดใช้งาน พื้นที่ทำงานปัจจุบันยังคงอยู่บนอุปกรณ์นี้", resetWorkspacePrompt: "ลบรถที่บันทึก Vehicle Case และประวัติการสนทนาจากพื้นที่ทำงานนี้หรือไม่?", cancel: "ยกเลิก", clearWorkspaceData: "ล้างข้อมูลพื้นที่ทำงาน", resetDeviceData: "ล้างข้อมูลอุปกรณ์", resetAccountData: "ล้างข้อมูลบัญชี", anonymousDataNote: "กิจกรรมแบบไม่เข้าสู่ระบบจะอยู่บนอุปกรณ์นี้ ควรเข้าสู่ระบบก่อนสร้าง Vehicle Case ที่สำคัญต่อธุรกิจ", syncedDataNote: "Vehicle Case และประวัติการสนทนาถูกเก็บในพื้นที่ทำงานบนเซิร์ฟเวอร์ที่แยกตามบัญชี พร้อมตรวจ Revision และบันทึกเหตุการณ์แบบเพิ่มต่อท้าย", syncing: "กำลังซิงก์", deviceLocal: "อยู่บนอุปกรณ์", workspaceSynced: "รถที่บันทึก Vehicle Case และประวัติถูกซิงก์กับบัญชีนี้แล้ว", workspaceSyncing: "กำลังซิงก์พื้นที่ทำงานนี้...", workspaceDeviceLocal: "พื้นที่ทำงานนี้อยู่บนอุปกรณ์เท่านั้นจนกว่าจะเข้าสู่ระบบบัญชีได้",
    vehicleNotFound: "ไม่พบรถคันนี้", vehicleNotFoundText: "รถคันนี้ไม่อยู่ในชุดที่ผ่านการตรวจสอบแล้ว", backToBrowse: "กลับไปค้นหารถ", nkSelection: "NK คัดเลือก", observedPriceCaption: "พบราคาประกาศเมื่อ {date} {fx} ราคาปัจจุบันยังไม่ได้ยืนยัน", generalVehicleLocation: "พื้นที่ทั่วไปของรถ", sourceVehicleDisclosure: "รถคันนี้มาจากแหล่งภายนอก ไม่ใช่สต็อกของ NK โดยตรง ข้อมูลผู้ขายและลิงก์ต้นทางเป็นข้อมูลภายใน", photoCounter: "{current} จาก {total}", openPhoto: "เปิดรูปที่ {number} แบบเต็มจอ", previousPhoto: "รูปก่อนหน้า", nextPhoto: "รูปถัดไป", closeGallery: "ปิดแกลเลอรีเต็มจอ",
    groundedVehicleSearch: "ค้นหารถจากข้อมูลที่ยืนยันได้", customerSafeMatches: "ผลลัพธ์สำหรับลูกค้า", resultCount: "{count} ผลลัพธ์", noApprovedMatch: "ยังไม่มีรถที่อนุมัติตรงเงื่อนไข", useFullFilters: "ใช้ตัวกรองทั้งหมด", noApprovedMatchText: "ยังไม่มีรถที่ผ่านการตรวจสอบตรงกับคำขอนี้ ระบบบันทึกคำขอแล้วและไม่ได้สร้างผลลัพธ์ขึ้นเอง",
    secureSource: "แหล่งข้อมูลที่ปลอดภัย", browseRealMarketplace: "ค้นหาใน Marketplace จริง", facebookSessionNotice: "Facebook จะเปิดด้วยบัญชีและ session ของคุณเอง NK ไม่สามารถอ่านรหัสผ่าน Cookie, MFA, CAPTCHA, การค้นหา หรือกิจกรรมอื่นใน Facebook ได้", openFacebookMarketplace: "เปิด Facebook Marketplace", marketplaceTabOpened: "เปิดแท็บ Marketplace แล้ว", readyToBrowse: "พร้อมค้นหา", marketplaceOpenedHelp: "ค้นหาตามปกติ เปิดรถ แล้วคัดลอกลิงก์หรือแชร์กลับมายัง NK", facebookExternalHelp: "Facebook เปิดภายนอกเว็บแอปเพราะไม่อนุญาตให้ฝังหน้าเว็บ", pasteFacebookLink: "วางลิงก์รถจาก Facebook", pasteVehicleLink: "วางลิงก์รถจากคลิปบอร์ด", translateAction: "แปลภาษา", checkCar: "ตรวจรถ", backToNk: "กลับ NK Cars", reloadMarketplace: "เปิด Facebook Marketplace ใหม่", nkVehicleActions: "การดำเนินการของ NK",
    facebookOpenedMessage: "เปิด Facebook ในแท็บที่ปลอดภัยแล้ว กลับมาที่นี่หลังคัดลอกหรือแชร์ลิงก์รถ", invalidClipboardLink: "คลิปบอร์ดไม่มีลิงก์รถ Facebook แบบ HTTPS ที่ถูกต้อง", linkDetected: "ตรวจพบลิงก์รถแล้ว บันทึกเข้า NK ได้เมื่อพร้อม", clipboardUnavailable: "ไม่สามารถอ่านคลิปบอร์ดได้ กรุณาวางลิงก์รถในช่องที่อยู่", validLinkFirst: "กรุณาวางลิงก์รถ Facebook แบบ HTTPS ที่ถูกต้องก่อน", chooseVehicleFirst: "เปิดรถใน Facebook คัดลอกลิงก์ แล้วกลับมาวางที่นี่",
    realMarketplaceFlow: "ขั้นตอนซื้อรถจาก Marketplace จริง", browseFacebookSaveNk: "ค้นหาใน Facebook แล้วบันทึกรถเข้า NK", sourceShareIntro: "ใช้บัญชี Facebook ของคุณค้นหา Marketplace ตามปกติ NK จะได้รับเฉพาะรถที่คุณเลือกแชร์", facebookSessionStays: "session Facebook ของคุณอยู่กับ Facebook", noFacebookCredentials: "NK ไม่เก็บรหัสผ่าน Facebook, คำตอบ MFA, CAPTCHA หรือ Cookie ของเบราว์เซอร์", stepSearchMarketplace: "ค้นหาและใช้ตัวกรองใน Facebook Marketplace ตามปกติ", stepOpenShare: "เปิดรถแล้วแตะ Share", stepChooseSaveNk: "เลือกบันทึกเข้า NK Cars เมื่อมีตัวเลือก", shareExtensionNotice: "ในแอป NK ที่รองรับ การแชร์จะเปิด NK และสร้าง Vehicle Case อัตโนมัติ iPhone ต้องใช้ NK iOS Share Extension ซึ่งเว็บแอปติดตั้งให้ไม่ได้", webAppCompanion: "เครื่องมือช่วยบนเว็บ", tryNkWebBrowser: "ลอง NK Web Browser", webBrowserIntro: "เปิด Facebook Marketplace จริง แล้วนำลิงก์รถที่เลือกกลับมาใช้คำสั่งของ NK และสร้าง Vehicle Case", openNkWebBrowser: "เปิด NK Web Browser", otherNkPaths: "ช่องทางอื่นของ NK", continueInsideNk: "ดำเนินการต่อใน NK", browseSavedResults: "ดูผลลัพธ์ NK ที่บันทึกไว้", lastResortPaste: "ทางเลือกสุดท้าย: วางลิงก์",
    saveToNkCars: "บันทึกเข้า NK Cars", lastResortFallback: "ทางเลือกสำรองด้วยลิงก์", creatingVehicleCase: "กำลังสร้าง Vehicle Case", pasteFacebookVehicleLink: "วางลิงก์รถจาก Facebook", importingSharedVehicle: "NK กำลังนำเข้ารถที่คุณแชร์และจะเปิดเคสให้อัตโนมัติ", fallbackOnlyNotice: "ใช้วิธีนี้เมื่ออุปกรณ์ไม่มีคำสั่งบันทึกเข้า NK Cars", browseInFacebook: "ค้นหาใน Facebook Marketplace", facebookLoginControl: "Facebook เปิดภายนอก NK และให้ Facebook ควบคุมการเข้าสู่ระบบ MFA และ session", stepBrowseSelect: "ค้นหาและเลือกรถจริง", stepShareCopy: "ใช้ Share หรือ Copy Link", stepReturnPaste: "กลับมาวางลิงก์ที่นี่", vehicleListingUrl: "ลิงก์ประกาศรถ", pasteAction: "วาง", importAnalyze: "นำเข้าและวิเคราะห์", sourceSafety: "NK เก็บเฉพาะลิงก์รถที่เลือกและหลักฐานที่เข้าถึงได้ ไม่เก็บรหัสผ่าน Facebook ไม่คัดลอก Cookie และไม่ข้าม MFA/CAPTCHA", openSourceListing: "เปิดประกาศต้นทาง", vehiclePhotoPending: "รอรูปภาพรถ", accessibleImages: "เข้าถึงรูปได้ {count} รูป", importedPreview: "ตัวอย่างข้อมูลนำเข้าที่ปลอดภัยสำหรับลูกค้า", workingFallback: "ทางเลือกสำรองที่ใช้งานได้", uploadScreenshotsPhotos: "อัปโหลด Screenshot / รูปภาพ", uploadThirty: "เลือกรูปรถคันเดียวได้สูงสุด 30 รูป ระบบจะวิเคราะห์รวมกันเป็นรถหนึ่งคัน", addMoreImages: "เพิ่มรูป", choosePhotos: "เลือกรูป / Screenshot", selectedCount: "เลือกแล้ว {count}/30 - รองรับ iPhone และ Android", listingTextLabel: "ข้อความประกาศ", listingTextPlaceholder: "วางชื่อรถ รายละเอียด ราคา เลขไมล์ และสเป็กที่นี่", saveManualReview: "บันทึกเพื่อตรวจสอบเอง", analyzeNkAi: "วิเคราะห์ด้วย NK AI", localEvidenceNotice: "หลักฐานที่อัปโหลดจะอยู่บนอุปกรณ์นี้จนกว่าจะเชื่อมพื้นที่เก็บสื่อส่วนตัวและบัญชีเจ้าของเคส", backBrowseVehicles: "กลับไปค้นหารถ",
    clipboardNoFacebookLink: "คลิปบอร์ดไม่มีลิงก์รถ Facebook", facebookLinkPasted: "วางลิงก์ Facebook แล้ว นำเข้าได้เมื่อพร้อม", clipboardPasteManual: "อ่านคลิปบอร์ดไม่ได้ กรุณาวางลิงก์ Facebook เอง", completeHttpsLink: "กรุณาวางลิงก์รถ HTTPS ที่สมบูรณ์", noConnectedImporter: "ยังไม่มีตัวนำเข้าสำหรับแหล่งนี้ ระบบเก็บลิงก์ไว้แล้ว กรุณาเพิ่มรูป Screenshot หรือข้อความประกาศ", listingUnreadable: "อ่านประกาศอัตโนมัติไม่ได้ กรุณาเพิ่มรูป Screenshot หรือข้อความประกาศ", partialImport: "เข้าถึงข้อมูลประกาศได้บางส่วน กรุณาตรวจข้อมูลและเพิ่มรูปสำหรับหลักฐานที่ขาด", accessibleImported: "นำเข้าหลักฐานที่เข้าถึงได้แล้ว แต่ยังไม่ได้ยืนยันว่ารถยังอยู่", sourceUnreachable: "session นี้เข้าถึงแหล่งข้อมูลไม่ได้ กรุณาเพิ่มรูป Screenshot หรือข้อความประกาศ", imagePrepFailed: "เตรียมรูปบางรูปไม่ได้ กรุณาลองรูปอื่น", aiNotConnected: "ยังไม่ได้เชื่อม NK AI แต่ยังบันทึกหลักฐานให้ตรวจเองได้", aiAnalyzeFailed: "NK AI วิเคราะห์หลักฐานไม่ได้ แต่ยังบันทึกให้ตรวจเองได้", aiAnalyzed: "NK AI วิเคราะห์หลักฐานทั้งหมดเป็นรถหนึ่งคันแล้ว กรุณาตรวจข้อมูลที่ไม่ทราบหรือความมั่นใจต่ำ", aiUnreachable: "ติดต่อ NK AI ไม่ได้ แต่ยังบันทึกหลักฐานให้ตรวจเองได้", evidencePrepared: "เตรียมเคสหลักฐานแล้ว สเป็ก ราคาต้นทาง และสถานะรถยังไม่ได้ยืนยัน",
    buyingBrowser: "Buying Browser", homeLabel: "หน้าแรก NK Cars Buying Browser", navLabel: "เมนู Buying Browser", mobileNavLabel: "เมนูมือถือ Buying Browser", openAccount: "เปิดบัญชี", deviceAccount: "บัญชีบนอุปกรณ์", nkAccount: "บัญชี NK", removeSaved: "นำ {vehicle} ออกจากรถที่บันทึก", removeSavedVehicle: "นำรถออกจากรายการบันทึก",
  },
};

export function normalizeLanguage(value) {
  return SUPPORTED_LANGUAGES.includes(value) ? value : "en";
}

export function detectSourceLanguage(text) {
  const value = String(text || "");
  if (/[฀-๿]/u.test(value)) return "th";
  if (/[㐀-鿿]/u.test(value)) return "zh-CN";
  if (/[A-Za-z]/.test(value)) return "en";
  return "unknown";
}

export function translate(language, key, variables = {}) {
  const dictionary = dictionaries[normalizeLanguage(language)] || dictionaries.en;
  const template = dictionary[key] || dictionaries.en[key] || key;
  return Object.entries(variables).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), template);
}

export function localizeListingSummary(listing, language) {
  const selected = normalizeLanguage(language);
  if (selected === "en") return listing.summary;
  const year = listing.year ?? (selected === "th" ? "รอตรวจสอบปี" : "年份待确认");
  const mileage = listing.mileageKm === null ? (selected === "th" ? "เลขไมล์รอตรวจสอบ" : "里程待确认") : `${listing.mileageKm.toLocaleString("en-US")} km`;
  if (selected === "zh-CN") return `${year} ${listing.brand} ${listing.model}，${listing.grade}，${listing.engine}，${listing.transmission}，${listing.drive}，${listing.body}，${mileage}。可售状态、价格和车况仍需核实。`;
  return `${year} ${listing.brand} ${listing.model} รุ่น ${listing.grade}, ${listing.engine}, เกียร์ ${listing.transmission}, ${listing.drive}, ${listing.body}, ${mileage} สถานะรถ ราคา และสภาพจริงยังต้องตรวจสอบ`;
}

export function localizeAvailability(status, language) {
  const selected = normalizeLanguage(language);
  if (selected === "en") return status;
  const labels = selected === "zh-CN" ? {
    "Availability Not Yet Confirmed": "可售状态尚未确认",
    "Availability Check Requested": "已申请确认可售状态",
    "Verified Available": "已确认可售",
    "Price Changed": "价格已变更",
    "Possibly Unavailable": "可能已不可售",
  } : {
    "Availability Not Yet Confirmed": "ยังไม่ได้ยืนยันว่ารถยังอยู่",
    "Availability Check Requested": "ส่งคำขอตรวจสอบสถานะแล้ว",
    "Verified Available": "ยืนยันว่ารถยังอยู่",
    "Price Changed": "ราคาเปลี่ยนแปลง",
    "Possibly Unavailable": "รถอาจไม่อยู่แล้ว",
  };
  return labels[status] || status;
}
